name: biertje
recipe: drupal9

config:
  via: apache:2.4
  php: "8.0"
  database: mariadb
  webroot: web

proxy:
  mailhog:
    - "mailhog.biertje.lndo.site"

services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://biertje.lndo.site"
